### ISSUE TITLE
Change license to AGPL

### ISSUE THREAD

**Issue by lucaswerkmeister** [lucaswerkmeister/ceylon-mode#12]
I’d like to change the license from GPLv3+ to AGPLv3+ – this isn’t primarily a program run over a network, but if someone runs an “Emacs in your browser” website or something like that, I’d still like to protect their users’ freedom.

@purcell, as the only other contributor: do you agree to make your contribution (#11) available under that license as well?

**Comment by purcell** [comment]
Sorry for the delay. Yes, that's absolutely fine with me.

**Comment by lucaswerkmeister** [comment]
Thanks! And no worries, this isn’t a very high-activity repository ;)
