### ISSUE TITLE
ceylon-mode does not work without (require 'cl)

### ISSUE THREAD

**Issue by xkr47** [lucaswerkmeister/ceylon-mode#4]
Loading ceylon-mode in vanilla emacs does not work (fails complaining that "concatenate" is not defined). Executing `(require 'cl)` before loading ceylon-mode in .emacs gets rid of the error.. but it feels a bit overkill to load another lisp to get it to work :stuck_out_tongue_winking_eye:

**Comment by lucaswerkmeister** [comment]
Workaround: 0cd125354f11bd5d4010abf33e8042882b1c84c9

But I agree that this should work without Common Lisp functions.
