### ISSUE TITLE
Is this mode a dead mode?

### ISSUE THREAD

**Issue by russel** [lucaswerkmeister/ceylon-mode#6]
Is this mode still viable? Is there something from https://github.com/bkc39/ceylon-mode that might be useful? Might it be worth noting that that one exists even if to say it should be ignored?

**Comment by lucaswerkmeister** [comment]
Well, I still have it installed locally and edit Ceylon files in Emacs fairly regularly, so I guess it’s viable? I just don’t have the time to improve it, but it works well enough for me.

I don’t think I’ve seen that other mode before, but as far as I can tell there’s not much I could take from it – as far as I see, it only highlights keywords, and my mode does that plus some more (off the top of my head: string templates, annotations, indentation). But I guess I can add a link to it to the README.

**Comment by russel** [comment]
Maybe put the mode into MELPA?

**Comment by lucaswerkmeister** [comment]
I guess I can upload a 0.1 version, yeah. I’ll look into it tomorrow.

**Comment by lucaswerkmeister** [comment]
I decided to add some more features first (code formatting support!), but I’ve now submitted melpa/melpa#4751 :)

**Comment by lucaswerkmeister** [comment]
MELPA package is now available, so closing now. But thanks for giving me the push I apparently needed :)

**Comment by russel** [comment]
I installed it 7 minutes after the production run created it. :-)

**Comment by lucaswerkmeister** [comment]
Ah, I wondered why the number of downloads was higher than just my own test download :D
